dataset:
  name: MNIST
  resize: [32, 32]
  normalize: false
  batch_size: 1

model_config:
  checkpoint_path: "./checkpoints/edl_MNIST_250430_15:36/model.pth"
  model:
    type: lenet
    num_classes: 10
  edl:
    enabled: True
    evidence_func: relu  # relu, softplus, exp

visualization:
  method: saliency         # or saliency
  random:
    is_random: False
    seed: 42
    target_indices: 0 # indices of the classes to visualize
  save_path: "./results"
